baseURL = 'http://wiedmann-trey.github.io/'
languageCode = 'en-us'
title = 'Trevor Wiedmann'

[params]
description = 'Computer graphics + vision developer and researcher'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
